//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntabaNet.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Agent()
        {
            this.Sales = new HashSet<Sale>();
        }
    
        public int ID { get; set; }
        public int LicenseeID { get; set; }
        public int AgentTypeID { get; set; }
        public int AgentStatusID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
    
        public virtual AgentStatus AgentStatus { get; set; }
        public virtual AgentType AgentType { get; set; }
        public virtual Licensee Licensee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sale> Sales { get; set; }
    }
}
