//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntabaNet.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IntabaNetData : DbContext
    {
        public IntabaNetData()
            : base("name=IntabaNetData")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Agent> Agents { get; set; }
        public virtual DbSet<AgentStatus> AgentStatus1 { get; set; }
        public virtual DbSet<AgentType> AgentTypes { get; set; }
        public virtual DbSet<Intermediary> Intermediaries { get; set; }
        public virtual DbSet<Licensee> Licensees { get; set; }
        public virtual DbSet<LicenseeType> LicenseeTypes { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<ProductUnderwriter> ProductUnderwriters { get; set; }
        public virtual DbSet<Sale> Sales { get; set; }
        public virtual DbSet<Underwriter> Underwriters { get; set; }
    }
}
